# config.yaml

PROD:
  # Unity Catalog Settings for Production
  catalog_name: workspace
  schema_name: default
  volume_name: yfinance_data
  # SQL data source
  sql_table_name: google_drive.gpw_data

TEST:
  # Unity Catalog Settings for Tests
  catalog_name: workspace
  schema_name: test_schema 
  volume_name: yfinance_test_data
  # SQL data source
  sql_table_name: google_drive.gpw_data 