# config.yaml

PROD:
  # Ustawienia Unity Catalog dla Produkcji
  catalog_name: workspace
  schema_name: default
  volume_name: yfinance_data
  # Źródło danych SQL
  sql_table_name: google_drive.gpw_data

TEST:
  # Ustawienia Unity Catalog dla Testów
  catalog_name: workspace
  schema_name: test_schema 
  volume_name: yfinance_test_data
  # Źródło danych SQL
  sql_table_name: google_drive.gpw_data 